name: daily-analytics
on:
  schedule:
    - cron: "5 6 * * *"   # 06:05 UTC ≈ 09:05 по Киеву
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pytrends snscrape pycountry babel python-telegram-bot==21.*
      - name: Run daily analytics
        env:
          TELEGRAM_BOT_TOKEN_APPROVAL: ${{ secrets.TELEGRAM_BOT_TOKEN_APPROVAL }}
          TELEGRAM_APPROVAL_CHAT_ID:   ${{ secrets.TELEGRAM_APPROVAL_CHAT_ID }}
          TELEGRAM_BOT_USERNAME:       ${{ secrets.TELEGRAM_BOT_USERNAME }}
        run: python ops/daily_analytics.py